apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler-pkgi-sa
  namespace: tkg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler-pkgi-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler-pkgi-sa
    namespace: tkg-system
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cluster-autoscaler-pkgi
  namespace: tkg-system
spec:
  serviceAccountName: cluster-autoscaler-pkgi-sa
  packageRef:
    refName: cluster-autoscaler.tanzu.vmware.com
    versionSelection:
      constraints: 1.26.2+vmware.1-tkg.2
  values:
  - secretRef:
      name: cluster-autoscaler-pkgi-data-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-pkgi-data-values
  namespace: tkg-system
stringData:
  values.yml: |
    ---
    arguments:
      ignoreDaemonsetsUtilization: true
      maxNodeProvisionTime: 15m
      maxNodesTotal: 0
      metricsPort: 8085
      scaleDownDelayAfterAdd: 10m
      scaleDownDelayAfterDelete: 10s
      scaleDownDelayAfterFailure: 3m
      scaleDownUnneededTime: 10m
    clusterConfig:
      clusterName: "tkg-cc-cas"
      clusterNamespace: "namespace-1"
    paused: false