apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    vm.name: db-vm
    role: db
  name: mysql-db
  namespace: namespace-1
spec:
  imageName: vmi-e1f344eb9636db690
  className: best-effort-small
  powerState: poweredOn
  storageClass: k8s-storage-policy
  networkInterfaces:
  - networkName:
    networkType: nsx-t
  vmMetadata:
      configMapName: mysql-db-cm
      transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-db-cm
    namespace: namespace-1
data:
  user-data: >-
    I2Nsb3VkLWNvbmZpZwoKc3NoX3B3YXV0aDogdHJ1ZQoKZ3JvdXBzOgogIC0gYWRtaW5ncm91cDogW3Jvb3Qsc3lzXQoKdXNlcnM6CiAgLSBuYW1lOiBkZXYKICAgIGdlY29zOiBEZXYgUy4gT3BzCiAgICBsb2NrX3Bhc3N3ZDogZmFsc2UKICAgIHBhc3N3ZDogJDYkbi96SnV5LngvTzBvUktIcCRzUkswd05tS2tUUlgyNnBvUlRWUElzWGl6NHU5U3ZWUjJldXpOVjdaWFI5RFRELkwzWGdIMFRnWlp5eGlHRTFNdy5CNkQ4WWNxQ3JMcHdEQ29SbkJRLgogICAgc3VkbzogQUxMPShBTEwpIE5PUEFTU1dEOkFMTAogICAgZ3JvdXBzOiBzdWRvLCB1c2VycywgYWRtaW4KICAgIHNoZWxsOiAvYmluL2Jhc2gKCndyaXRlX2ZpbGVzOgogIC0gY29udGVudDogfAogICAgICAgQUxURVIgVVNFUiAncm9vdCdAJ2xvY2FsaG9zdCcgSURFTlRJRklFRCBXSVRIIG15c3FsX25hdGl2ZV9wYXNzd29yZCBCWSAncGFzc3dvcmQnOwogICAgYXBwZW5kOiB0cnVlCiAgICBwYXRoOiAvYWx0ZXJ1c2VyLnR4dAoKICAtIGNvbnRlbnQ6IHwKICAgICAgIENSRUFURSBVU0VSICdkZXZvcHMnQCclJyBJREVOVElGSUVEIFdJVEggbXlzcWxfbmF0aXZlX3Bhc3N3b3JkIEJZICdwYXNzd29yZCc7CiAgICAgICBDUkVBVEUgREFUQUJBU0UgZGVtbzsKICAgICAgIEdSQU5UIEFMTCBQUklWSUxFR0VTIE9OIGRlbW8uKiBUTyAnZGV2b3BzJ0AnJSc7CgogICAgICAgQ1JFQVRFIFRBQkxFIGRlbW8udXNlciAoCiAgICAgICAgIGlkIElOVEVHRVIgUFJJTUFSWSBLRVkgQVVUT19JTkNSRU1FTlQsCiAgICAgICAgIHVzZXJuYW1lIHZhcmNoYXIoMjU1KSBOT1QgTlVMTCwKICAgICAgICAgcGFzc3dvcmQgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogICAgICAgICBVTklRVUUgKHVzZXJuYW1lKQogICAgICAgKTsKCgogICAgICAgQ1JFQVRFIFRBQkxFIGRlbW8uZW50cnkgKAogICAgICAgICBpZCBJTlRFR0VSIFBSSU1BUlkgS0VZIEFVVE9fSU5DUkVNRU5ULAogICAgICAgICBhdXRob3JfaWQgSU5URUdFUiBOT1QgTlVMTCwKICAgICAgICAgY3JlYXRlZCBUSU1FU1RBTVAgTk9UIE5VTEwgREVGQVVMVCBDVVJSRU5UX1RJTUVTVEFNUCwKICAgICAgICAgdGl0bGUgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogICAgICAgICBib2R5IHZhcmNoYXIoNTQwMCkgTk9UIE5VTEwsCiAgICAgICAgIEZPUkVJR04gS0VZIChhdXRob3JfaWQpIFJFRkVSRU5DRVMgdXNlciAoaWQpCiAgICAgICApOwoKICAgICAgIElOU0VSVCBJTlRPIGRlbW8udXNlciAodXNlcm5hbWUscGFzc3dvcmQpIFZBTFVFUygnSmVyZW15JywnZGV2b3BzMTIzJyk7CiAgICAgICBJTlNFUlQgSU5UTyBkZW1vLmVudHJ5IChhdXRob3JfaWQsdGl0bGUsYm9keSkgVkFMVUVTKDEsIldlbGNvbWUgdG8gdGhlIHJlcXVlc3QgcGFnZSwgdGhpcyBpcyB0aGUgZmlyc3QgZW50cnkiLCJUaGlzIGVudHJ5IGlzIG93bmVkIGJ5IEplcmVteSBhbmQgY2FuIG9ubHkgYmUgbW9kaWZpZWQgYnkgaGltLiBZb3UgY2FuIGNyZWF0ZSB5b3VyIG93biBwb3N0IGJ5IHJlZ2lzdGVyaW5nIGFuZCBsb2dnaW5nIGluISIpOwoKICAgIGFwcGVuZDogdHJ1ZQogICAgcGF0aDogL2luaXQuc3FsCgpydW5jbWQ6CiAgLSBzdWRvIGFwdCB1cGRhdGUKICAtIHN1ZG8gYXB0IC15IGluc3RhbGwgbXlzcWwtc2VydmVyCiAgLSBzdWRvIHN5c3RlbWN0bCBzdGFydCBteXNxbC5zZXJ2aWNlCiAgLSBzdWRvIG15c3FsIDwgL2FsdGVydXNlci50eHQKICAtIG15c3FsIC11IHJvb3QgLXBwYXNzd29yZCA8IC9pbml0LnNxbAogIC0gc3VkbyBzZWQgLWkgJzAsL2JpbmQtYWRkcmVzcy9zLy8jYmluZC1hZGRyZXNzLycgL2V0Yy9teXNxbC9teXNxbC5jb25mLmQvbXlzcWxkLmNuZgogIC0gc3VkbyBlY2hvIHNraXAtbmFtZS1yZXNvbHZlID4+IC9ldGMvbXlzcWwvbXlzcWwuY29uZi5kL215c3FsZC5jbmYKICAtIHN1ZG8gc3lzdGVtY3RsIHJlc3RhcnQgbXlzcWwuc2VydmljZQ==
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: mysql-db
  namespace: namespace-1
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    vm.name: db-vm
  type: LoadBalancer