apiVersion: v1
kind: Secret
metadata:
  name: cli-vm-bootstrap-secret
  namespace: namespace-1
  labels:
    vm-selector: cli-vm
stringData:
  user-data: |
    #cloud-config
        ssh_pwauth: true
        groups:
        - admingroup: [root,sys]
        users:
          - name: devops
            gecos: Dev S. Ops
            lock_passwd: false
            passwd: $6$n/zJuy.x/O0oRKHp$sRK0wNmKkTRX26poRTVPIsXiz4u9SvVR2euzNV7ZXR9DTD.L3XgH0TgZZyxiGE1Mw.B6D8YcqCrLpwDCoRnBQ.
            # Password set to DevOps123
            sudo: ALL=(ALL) NOPASSWD:ALL
            groups: sudo, users, admin
            shell: /bin/bash
        runcmd:
          # Update packages
          - sudo apt-get update && sudo apt-get upgrade
          # Install tools
          - sudo apt install -y ca-certificates curl wget gnupg net-tools zip unzip jq zsh bat bash-completion whois 
          # Install kubectl
          - curl curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          - sudo echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          - sudo apt-get update && sudo apt-get install -y kubectl
          # Install kubectl-vsphere plugin
          - curl -ks https://192.168.30.34/wcp/plugin/linux-amd64/vsphere-plugin.zip -o /tmp/vsphere-plugin.zip
          - unzip -qn /tmp/vsphere-plugin.zip -d /tmp
          - sudo install /tmp/bin/kubectl-vsphere /usr/local/bin
          # Install vCenter certificates
          - wget https://vcenter-01.vmw.lab/certs/download.zip --no-check-certificate
          - unzip download.zip
          - cp certs/lin/351d2e9c.0 ca.crt
          - sudo cp ca.crt /usr/local/share/ca-certificates
          - sudo update-ca-certificates
          # Mount Persistent Volume
          - parted -s /dev/sdb -- mkpart primary ext4 0% 100%
          - mkfs -t ext4 /dev/sdb1
          - mkdir -p /mnt/pv
          - echo '/dev/sdb1 /mnt/pv ext4 defaults 0 2' >>/etc/fstab
          - mount -a
          # Install Docker
          - curl -fsSL https://get.docker.com -o get-docker.sh
          - sudo sh get-docker.sh
          - sudo usermod -aG docker devops
          # Install Carvel tools
          - wget -O- https://carvel.dev/install.sh > install.sh
          - sudo bash install.sh
          # Install Packer
          - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          - sudo apt-get update && sudo apt-get install packer
          # Install Ansible
          - sudo add-apt-repository --yes --update ppa:ansible/ansible
          - sudo apt install -y ansible
          # Install Packer plugins
          - packer plugins install github.com/hashicorp/vsphere
          - packer plugins install github.com/hashicorp/ansible