apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tkg-cc-1
  namespace: namespace-1
  labels:
    tkg-cluster-selector: tkg-cc-1
spec:
  clusterNetwork:
    cni:
      name: antrea
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: tanzukubernetescluster
    version: v1.30.1---vmware.1-fips-tkg.5
    variables:
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: k8s-storage-policy
      - name: nodePoolVolumes
        value: []
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon
    workers:
      machineDeployments:
        - class: node-pool
          name: tkg-cluster-nodepool-oq6r
          replicas: 1
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
          variables:
            overrides:
              - name: vmClass
                value: best-effort-xsmall
              - name: nodePoolVolumes
                value:
                  - name: containerd
                    mountPath: /var/lib/containerd
                    storageClass: k8s-storage-policy
                    capacity:
                      storage: 5Gi
        - class: node-pool
          name: tkg-cluster-nodepool-az3u
          replicas: 1
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon